sudo: required
dist: trusty


cache:
  npm: true
  directories:
    - /home/travis/build/hasadna/open_pension/server/data/OpenPensionCSV
    - "$HOME/.npm"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - 3.6

git:
  lfs_skip_smudge: true

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - TRAVIS_CI_OPERATOR=1
    - secure: "PrtG3JfkkilQRkE6iIBwjmOPYvU4axynlOi13EPHgW2eiZKKylBSj0C+VdvollUIwMSDBGKOBqNICuGJqfA9nv+F0WyTyzJmLhlDnFkiAS8laXKqlrH5w10CMl9BCwu0aJykKE7Ufd3GnqHVlspZG995Gp2nByC9RajSADUxE69DFm6yMT+Ec6Z9g+5nmylkBN2MFS20j3lmGn2l5s8TaBborSobPHzH6UBrYCLjM/uqBjU0DpzJy8wT9ClcYp4vO/+1X4TOpxUOOXINvPtn+gakkHK+yPsJzlCSqny+tNkRh5aKB9EHXrW3pdvcAbCsk0eUARIwM2YIrk7k+K+43DIrDYvgcKSacpDQJ3dVbQ8WgBT7lD/RD655ofGoloFOCZ65fUXN04EV2JjU2H2xBzY/o8/kJ91Wm5U5TBJYTo4ESMg9Bsdh/OY9Mj1cNxD0pxo9dHnE5VzZpCXSZwcO2U29uK1m7BK8DN1op5dpXfr3wEoDCPGLAn+6XRj1GyyMM0InilV60GLqQvCkbMqlYSalgeEZ3wqdPKdTxeaff6dK4hDO6AIIo/FqBtz7seSn6Y6jZ60l85lDgRwr+tpBnHAJ9ebrrwSlfohe5MjOesdaEdmTwl8d0ZIC5LT3CAiD8D8ngybf1LtOAIvtWeEDCblGMmOjpRuu0R2M0S2Ecww="
    - secure: "ugeA6ws1C120hfgp/ib/IrcLrmbhSZZPDOiyLOcFxi2O3lpgGaiWMTBSsGZt0OD1hVa9WVKHuN385hZvfKWKICBSvCfGWIXnlzq3G0+aAC7TPQHGLBddGSKnT+1AoVIJYJb05XGwszY17PshMwlE+h+jbP9IxGIOUohk0G8wP/5fQi6wJWdFgMSukrySVlUGkmOFuH0lbTCRLla2NqQ2EZDMMJXEXmyCg2t0HUW8RvFGJeiqHo3atBgeYt9ABKWH3Z/ObUvt9cuC0XGBg8jwXz/jsjMuslfokAlaSP7Z7z0SlDcXhYR5LZmtLEbuGMzGAlblb3NdiOWvgpTkWKY16/l8sXKRxWOzzAhsNTAEl9zabCiKGAz0UbJtBVZ1TOOKyb5M+h8muVl54/nC8nJujXgOOe5SDp/zSoNyyzB7AQYCEK7cY/khUIe0YPEb2vp8CGrWZK7Rqh9QPGSvc+zezsm+bxkM1VPL72CC6UYjbUFMx6qv3i1irEDS0Mb3H5tWhgWsTmRMdR807RFoRr2aZka9zgXT8Nrom1snIVdkwvOMPhHANwttK074xqJSo3EDiocINb1zBXB7YJonRQMlfXLuQZ5vQdCKNPOOOhoT5czi3xgK3If8W8zG0uWvFDnVfSXl2vrP9uWqZt3aTK8L+vxqAB9r3VKhqiyTAMk6Hqg="
#before_install:
  #- npm install -g npm@latest codecov
  #- export CHROME_BIN=chromium-browser
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- cd /home/travis/build/hasadna/open_pension/client
  #- docker pull hasadna/open-pension-client
  #- docker build -t hasadna/open-pension-client --cache-from hasadna/open-pension-client .
  #- cd /home/travis/build/hasadna/open_pension/server
  #- docker pull hasadna/open-pension-server
  #- docker build -t hasadna/open-pension-server --cache-from hasadna/open-pension-server .
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

install:
  # Server
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pip install coverage pycodestyle flake8 isort

  # Client
  #- cd /home/travis/build/hasadna/open_pension/client
  #- npm ci
  # CI/CD
  - curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
  - bash $HOME/bin/travis_ci_operator.sh init
  - travis_ci_operator.sh docker-login
script:
  # Client
  #- cd /home/travis/build/hasadna/open_pension/client
  #- npm run lint
  #- npm run test
  #- npm run e2e

  # Server
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage run --source='.' manage.py test
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage xml
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pycodestyle --show-source --max-line-length=120 --exclude=pension/migrations --show-pep8 .
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server isort . --recursive --check-only
  - docker pull hasadna/open-pension-server:latest
  - docker build --cache-from hasadna/open-pension-server:latest  -t hasadna/open-pension-server:latest ./server
  - docker pull hasadna/open-pension-client:latest
  - docker build --cache-from hasadna/open-pension-client:latest -t hasadna/open-pension-client:latest ./client

after_script:
  - cd /home/travis/build/hasadna/open_pension && codecov -t 4e44efc7-43b7-42e3-a122-4042d83e19ff

deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
    condition: $TRAVIS_TAG = "" && $TRAVIS_PULL_REQUEST = "false"